autoload     usr/share/vim/addons
doc          usr/share/vim/addons
plugin       usr/share/vim/addons
python/ycm   usr/share/vim/addons/python

third_party/ycmd/ycmd                usr/share/vim/addons/third_party/ycmd
third_party/ycmd/CORE_VERSION        usr/share/vim/addons/third_party/ycmd
third_party/ycmd/.ycm_extra_conf.py  usr/share/vim/addons/third_party/ycmd
third_party/ycmd/ycm_*.so            usr/share/vim/addons/third_party/ycmd

third_party/ycmd/third_party/bottle          usr/share/vim/addons/third_party/ycmd/third_party
third_party/ycmd/third_party/clang           usr/share/vim/addons/third_party/ycmd/third_party
third_party/ycmd/third_party/clangd/output   usr/share/vim/addons/third_party/ycmd/third_party/clangd
third_party/ycmd/third_party/frozendict      usr/share/vim/addons/third_party/ycmd/third_party
third_party/ycmd/third_party/waitress        usr/share/vim/addons/third_party/ycmd/third_party
